language: "generic"
services: -docker

before_install:
  - docker build -t s3f4/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true s3f4/react-test npm test -- --coverage

after_success:
  - docker build -t s3f4/multi-client ./client
  - docker build -t s3f4/multi-nginx ./nginx
  - docker build -t s3f4/multi-server ./server
  - docker build -t s3f4/multi-worker ./worker

  #LOGIN docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push s3f4/multi-client
  - docker push s3f4/multi-nginx
  - docker push s3f4/multi-server
  - docker push s3f4/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-096703671894"
  bucket_path: "test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
